export const valoData = [
  {
    agent: "astra",
    image: "https://i.imgur.com/NMkcklg.png",
    musics: [
      "https://www.youtube.com/embed/Q-RCIu45VIc",
      "https://www.youtube.com/embed/4Det9_0EdNM",
      "https://www.youtube.com/embed/_SZb3T6rjJk",
      "https://www.youtube.com/embed/YUmSu_54478",
      "https://www.youtube.com/embed/IoFOXgIme9M",
      "https://www.youtube.com/embed/Iq4gw87-nRQ",
      "https://www.youtube.com/embed/S1yn2GtDakM",
      "https://www.youtube.com/embed/ytI9A0u88Bk",
      "https://www.youtube.com/embed/Dm-foWGDBF0",
      "https://www.youtube.com/embed/R2hBakhj4o0",
      "https://www.youtube.com/embed/mTjQq5rMlEY",
      "https://www.youtube.com/embed/4y0w2-rgWa0",
      "https://www.youtube.com/embed/Ak4vLEBxIo4",
      "https://www.youtube.com/embed/SXoWrKHp9f8",
      "https://www.youtube.com/embed/wy_j--ljb9w",
      "https://www.youtube.com/embed/FxRwLVoP3bo",
      "https://www.youtube.com/embed/yaCNI_W-lNQ",
      "https://www.youtube.com/embed/O0dLpnLBcKk",
    ],
  },
  {
    agent: "phoenix",
    image: "https://i.imgur.com/H4dCwgz.png",
    musics: [
      "https://www.youtube.com/embed/jWNC_OY4uzs",
      "https://www.youtube.com/embed/Zm7Zya6Hl50",
      "https://www.youtube.com/embed/mjaayCARwro",
      "https://www.youtube.com/embed/xBjXBNBdU9c",
      "https://www.youtube.com/embed/sw4r0k8WWqU",
      "https://www.youtube.com/embed/lQNZrZWYZBY",
      "https://www.youtube.com/embed/Guc3xSj7wQs",
      "https://www.youtube.com/embed/ub5uPEHD_rU",
      "https://www.youtube.com/embed/r_Q40kOt9X0",
      "https://www.youtube.com/embed/42FIkZCaSFg",
      "https://www.youtube.com/embed/3WHm6tfvKlk",
      "https://www.youtube.com/embed/gh72dXr4fTM",
      "https://www.youtube.com/embed/DgVN3n4p9GU",
      "https://www.youtube.com/embed/A3hx1xqYxl4",
      "https://www.youtube.com/embed/l0U7SxXHkPY",
      "https://www.youtube.com/embed/doaNcTKnpxs",
    ],
  },
  {
    agent: "brimstone",
    image: "https://i.imgur.com/jWd1zGh.png",
    musics: [
      "https://www.youtube.com/embed/0XVCc5zwPlU",
      "https://www.youtube.com/embed/pyZlRfu33Tg",
      "https://www.youtube.com/embed/HhXysqgD21c",
      "https://www.youtube.com/embed/fzR1-OacD8o",
      "https://www.youtube.com/embed/3ITF4HoRZRY",
      "https://www.youtube.com/embed/2g5xkLqIElU",
      "https://www.youtube.com/embed/aDbY0ywFRSQ",
      "https://www.youtube.com/embed/KDMvN45sjo4",
      "https://www.youtube.com/embed/K09_5IsgGe8",
      "https://www.youtube.com/embed/5oWyMakvQew",
      "https://www.youtube.com/embed/jBx9gQyiYoo",
      "https://www.youtube.com/embed/aJg4OJxp-co",
      "https://www.youtube.com/embed/nfrSIUE3iAE",
      "https://www.youtube.com/embed/t60roHM1t7o",
    ],
  },
  {
    agent: "sage",
    image: "https://i.imgur.com/ysHh9F6.png",
    musics: [
      "https://www.youtube.com/embed/sRbW4_uwHHw",
      "https://www.youtube.com/embed/XfuMEmcz3k0",
      "https://www.youtube.com/embed/FPkg6QnpOYQ",
      "https://www.youtube.com/embed/STUJbxWBGGs",
      "https://www.youtube.com/embed/lW9ep22YmlM",
      "https://www.youtube.com/embed/Nqqc2FHf9Ug",
      "https://www.youtube.com/embed/h7MYJghRWt0",
      "https://www.youtube.com/embed/ZHhqwBwmRkI",
      "https://www.youtube.com/embed/omgSWqwVTjY",
      "https://www.youtube.com/embed/O6N-qYPE6qc",
      "https://www.youtube.com/embed/e76qTrz6PlI",
    ],
  },
  {
    agent: "sova",
    image: "https://i.imgur.com/J2jMUG6.png",
    musics: [
      "https://www.youtube.com/embed/I_A2725uRL0",
      "https://www.youtube.com/embed/7jFy3A-qOi0",
      "https://www.youtube.com/embed/OlSxmQID9mc",
      "https://www.youtube.com/embed/sZUQMX_m1Zg",
      "https://www.youtube.com/embed/xn5MglF01iA",
      "https://www.youtube.com/embed/ig4IGBQupdg",
      "https://www.youtube.com/embed/qMJNP18TMTo",
      "https://www.youtube.com/embed/NBp9mNOFDLk",
      "https://www.youtube.com/embed/Yuz6icTJrk4",
    ],
  },
  {
    agent: "viper",
    image: "https://i.imgur.com/QpRZS7V.png",
    musics: [
      "https://www.youtube.com/embed/_lnXQ7kaa8E",
      "https://www.youtube.com/embed/6gmswmbosYo",
      "https://www.youtube.com/embed/oHkuMMb2qRA",
      "https://www.youtube.com/embed/60oHeAHe1Tc",
      "https://www.youtube.com/embed/1u8rIx65QgA",
      "https://www.youtube.com/embed/AXekXn25GRs",
      "https://www.youtube.com/embed/PvVhUo-PvVI",
      "https://www.youtube.com/embed/c4iyEXDStgk",
      "https://www.youtube.com/embed/B1o2UCLvD38",
      "https://www.youtube.com/embed/dhZTNgAs4Fc",
      "https://www.youtube.com/embed/9m8URzU21jc",
      "https://www.youtube.com/embed/BaLW9jk3748",
      "https://www.youtube.com/embed/psZuC10Oa4E",
    ],
  },
  {
    agent: "cypher",
    image: "https://i.imgur.com/IPwmCDX.png",
    musics: [
      "https://www.youtube.com/embed/ltcW6kviX6o",
      "https://www.youtube.com/embed/UPed54W5iL4",
      "https://www.youtube.com/embed/M1N_wbhAfQ4",
      "https://www.youtube.com/embed/Xk_MN0BG_aI",
      "https://www.youtube.com/embed/FwBn2_GPxEQ",
      "https://www.youtube.com/embed/i_T2V8ahNWw",
      "https://www.youtube.com/embed/_7Inklujb3Q",
      "https://www.youtube.com/embed/ImllpvDwbQ8",
      "https://www.youtube.com/embed/j9KKh215HTs",
      "https://www.youtube.com/embed/W8VymwVGHZw",
      "https://www.youtube.com/embed/aWfoSZY2duo",
    ],
  },
  {
    agent: "reyna",
    image: "https://i.imgur.com/V8GFe0q.png",
    musics: [
      "https://www.youtube.com/embed/hRIUfMzYXKg",
      "https://www.youtube.com/embed/ceJ-t_naYHQ",
      "https://www.youtube.com/embed/MTdj-6Bd5wk",
      "https://www.youtube.com/embed/w2Ro8cgsmss",
      "https://www.youtube.com/embed/wfN4PVaOU5Q",
      "https://www.youtube.com/embed/DPIv7awI-1A",
      "https://www.youtube.com/embed/AOwRK0xYK-A",
      "https://www.youtube.com/embed/rs5ecH8Lh3s",
      "https://www.youtube.com/embed/Q9jNSwmEQ3s",
      "https://www.youtube.com/embed/tksolV5Gkso",
      "https://www.youtube.com/embed/GtSRKwDCaZM",
    ],
  },
  {
    agent: "killjoy",
    image: "https://i.imgur.com/u1Njq61.png",
    musics: [
      "https://www.youtube.com/embed/1QMG2QjsjdA",
      "https://www.youtube.com/embed/DuRO3uzWESU",
      "https://www.youtube.com/embed/kTJczUoc26U",
      "https://www.youtube.com/embed/D9G1VOjN_84",
      "https://www.youtube.com/embed/Jmz8CXm8JLY",
      "https://www.youtube.com/embed/HyHNuVaZJ-k",
    ],
  },
  {
    agent: "breach",
    image: "https://i.imgur.com/a5RTejx.png",
    musics: [
      "https://www.youtube.com/embed/4HX6nSlBGss",
      "https://www.youtube.com/embed/NR7dG_m3MsI",
      "https://www.youtube.com/embed/yi9V-7Xx1UI",
      "https://www.youtube.com/embed/rrqIacO9g_g",
      "https://www.youtube.com/embed/yUlLa_6wTnw",
      "https://www.youtube.com/embed/hG4AMswOA0w",
      "https://www.youtube.com/embed/dM_Ut_v_Vm8",
      "https://www.youtube.com/embed/Pt7kmByAPxI",
      "https://www.youtube.com/embed/edBYB1VCV0k",
      "https://www.youtube.com/embed/e4yq4FIfiP8",
      "https://www.youtube.com/embed/KxOhc-dfEDY",
      "https://www.youtube.com/embed/vhhXOSHCNp4",
      "https://www.youtube.com/embed/iPW9AbRMwFU",
      "https://www.youtube.com/embed/mHAWJKmMTRQ",
    ],
  },
  {
    agent: "omen",
    image: "https://i.imgur.com/ufpcDty.png",
    musics: [
      "https://www.youtube.com/embed/KnT6vL_o4KU",
      "https://www.youtube.com/embed/Fuz4ZfMX2rk",
      "https://www.youtube.com/embed/d2RJBJnalxA",
      "https://www.youtube.com/embed/PoMmxLSMj3I",
      "https://www.youtube.com/embed/K9prnm9BNxM",
      "https://www.youtube.com/embed/M0NRmS-Jxws",
      "https://www.youtube.com/embed/JH8p64u9JW0",
      "https://www.youtube.com/embed/B8IFOgQenMM",
      "https://www.youtube.com/embed/9hv1nToG-7s",
      "https://www.youtube.com/embed/JRUPUKPBS9A",
      "https://www.youtube.com/embed/0YsyRBQdQrU",
      "https://www.youtube.com/embed/lMxF7-i5pTA",
      "https://www.youtube.com/embed/O9f1MJW7DAM",
    ],
  },
  {
    agent: "iso",
    image: "https://i.imgur.com/HrNklFW.png",
    musics: [
      "https://www.youtube.com/embed/QAAap0ceNbo",
      "https://www.youtube.com/embed/boz5BU1KdIw",
      "https://www.youtube.com/embed/h1_mc9qeTwE",
      "https://www.youtube.com/embed/v7_PRqsf2JQ",
      "https://www.youtube.com/embed/EIUkuWV8P8g",
      "https://www.youtube.com/embed/lrtI1oAhXws",
      "https://www.youtube.com/embed/lO0j8SOFxko",
      "https://www.youtube.com/embed/Ec685-RotlE",
      "https://www.youtube.com/embed/rlLC2Z0zTD4",
      "https://www.youtube.com/embed/EBhE2MCDpQk",
      "https://www.youtube.com/embed/p0ZNgsupy0o",
      "https://www.youtube.com/embed/ZTjmuHxVIkk",
      "https://www.youtube.com/embed/EUn0bOM5smw",
      "https://www.youtube.com/embed/tk3qWyzcEpE",
      "https://www.youtube.com/embed/yTRf4GSH0Kg",
      "https://www.youtube.com/embed/APtdNDijtv0",
      "https://www.youtube.com/embed/eXWR0o5RH8k",
      "https://www.youtube.com/embed/fvYmPhenwUs",
    ],
  },
  {
    agent: "deadlock",
    image: "https://i.imgur.com/HBEYXY4.png",
    musics: [
      "https://www.youtube.com/embed/V-4ghSTKpko",
      "https://www.youtube.com/embed/Y3j488fXd8w",
      "https://www.youtube.com/embed/zTYBFBgtFDM",
      "https://www.youtube.com/embed/loU77nk02lI",
      "https://www.youtube.com/embed/ZlMfd91rM1s",
      "https://www.youtube.com/embed/nOCUJndpyJ8",
      "https://www.youtube.com/embed/p1jW8FLb0YE",
      "https://www.youtube.com/embed/cfVSuywJ1IM",
      "https://www.youtube.com/embed/nSKMKAt-PLo",
      "https://www.youtube.com/embed/nr4Hj_fNyj8",
      "https://www.youtube.com/embed/lY2yjAdbvdQ",
      "https://www.youtube.com/embed/VyTrWCjmyrE",
      "https://www.youtube.com/embed/WPBCsWfERkE",
      "https://www.youtube.com/embed/rKfA4qUEB8k",
      "https://www.youtube.com/embed/7sLPNW6by1Q",
      "https://www.youtube.com/embed/vc3d5L3xF8I",
      "https://www.youtube.com/embed/6p5ICkEB7IA",
      "https://www.youtube.com/embed/7mJvES0uDbo",
    ],
  },
  {
    agent: "jett",
    image: "https://i.imgur.com/R7wQ3HK.png",
    musics: [
      "https://www.youtube.com/embed/xU2U73Tk-DM",
      "https://www.youtube.com/embed/gAzdJCPdkJ4",
      "https://www.youtube.com/embed/Y93Jjvhz1jg",
      "https://www.youtube.com/embed/ir7G_H0LFJw",
      "https://www.youtube.com/embed/aeRMzoA-XQI",
      "https://www.youtube.com/embed/aKl7-v-iCaA",
      "https://www.youtube.com/embed/b73BI9eUkjM",
      "https://www.youtube.com/embed/gVx3kKbRkqc",
      "https://www.youtube.com/embed/unA029iqiZM",
      "https://www.youtube.com/embed/FKXSh14svlQ",
      "https://www.youtube.com/embed/I3uzROnFGnA",
      "https://www.youtube.com/embed/Wpm07-BGJnE",
      "https://www.youtube.com/embed/ObzvA8tx9aA",
      "https://www.youtube.com/embed/CMla2ZIz7-4",
      "https://www.youtube.com/embed/GpYOfM_PwZg",
      "https://www.youtube.com/embed/WAo8X-rIt8k",
    ],
  },
  {
    agent: "raze",
    image: "https://i.imgur.com/oQV4kTB.png",
    musics: [
      "https://www.youtube.com/embed/GaW75lLt2y0",
      "https://www.youtube.com/embed/LyX8spKe_is",
      "https://www.youtube.com/embed/GwcvcTVbji0",
      "https://www.youtube.com/embed/kQCSEwe5i1g",
      "https://www.youtube.com/embed/8qd2zjuB3q4",
      "https://www.youtube.com/embed/MkKTtNbZzWw",
      "https://www.youtube.com/embed/H5VRjJ6n-CE",
      "https://www.youtube.com/embed/F5BuRldkKHc",
      "https://www.youtube.com/embed/m_YuGaaUuWU",
      "https://www.youtube.com/embed/3qdKnXaQ8Zw",
      "https://www.youtube.com/embed/3zxPluMRilI",
      "https://www.youtube.com/embed/l21ZcAB95cs",
      "https://www.youtube.com/embed/zsVxbZAWe5E",
      "https://www.youtube.com/embed/Yj9A6SXNwZ4",
    ],
  },
  {
    agent: "skye",
    image: "https://i.imgur.com/FS0n8Cq.png",
    musics: [
      "https://www.youtube.com/embed/PNWsW6c6t8g",
      "https://www.youtube.com/embed/D_EnyikMsEU",
      "https://www.youtube.com/embed/L9HYJbe9Y18",
      "https://www.youtube.com/embed/GQlefVvleRc",
      "https://www.youtube.com/embed/cNizeRa8DZ4",
      "https://www.youtube.com/embed/PkiIPzG37vQ",
      "https://www.youtube.com/embed/Ytgx9aiGHkU",
      "https://www.youtube.com/embed/ew5Lapq7m00",
      "https://www.youtube.com/embed/sBzrzS1Ag_g",
      "https://www.youtube.com/embed/n46ifZGwaAA",
      "https://www.youtube.com/embed/LniYWYmNXiM",
      "https://www.youtube.com/embed/pPsBFPX_yU4",
      "https://www.youtube.com/embed/xFQicNr0k0o",
    ],
  },
  {
    agent: "neon",
    image: "https://i.imgur.com/KlRXPmp.png",
    musics: [
      "https://www.youtube.com/embed/B6eLbmLGUyc",
      "https://www.youtube.com/embed/B7wFKkEq0As",
      "https://www.youtube.com/embed/nO4nf56ycdg",
      "https://www.youtube.com/embed/RdntuSSNv1I",
      "https://www.youtube.com/embed/s3GoSXSFDQU",
      "https://www.youtube.com/embed/nBIZXgv-WwU",
      "https://www.youtube.com/embed/35jH-_3VEzE",
      "https://www.youtube.com/embed/hgF1HI_kW6s",
      "https://www.youtube.com/embed/-aKU0BeEbzw",
      "https://www.youtube.com/embed/BYJ23QAx_L8",
      "https://www.youtube.com/embed/463dTV09owQ",
      "https://www.youtube.com/embed/l7uB0DG2jMA",
      "https://www.youtube.com/embed/xPs2ag4lRGk",
      "https://www.youtube.com/embed/dNCWe_6HAM8",
    ],
  },
  {
    agent: "yoru",
    image: "https://i.imgur.com/4OAgkor.png",
    musics: [
      "https://www.youtube.com/embed/mN9vfK9ZZRo",
      "https://www.youtube.com/embed/aPy95-le6R0",
      "https://www.youtube.com/embed/1TbEU1ptCkc",
      "https://www.youtube.com/embed/uefzKECyJrc",
      "https://www.youtube.com/embed/uq3J8C51bAY",
      "https://www.youtube.com/embed/yA4R9qLa26E",
      "https://www.youtube.com/embed/sTKjPRCHnWw",
      "https://www.youtube.com/embed/Jkg0S_2-Ncc",
      "https://www.youtube.com/embed/qENYMXG371k",
      "https://www.youtube.com/embed/slpWEl7nTwk",
      "https://www.youtube.com/embed/AZ0z9eqgs6k",
      "https://www.youtube.com/embed/FKoNh_naWms",
      "https://www.youtube.com/embed/oCyjhOku7lw",
      "https://www.youtube.com/embed/HduraQWs_6E",
      "https://www.youtube.com/embed/6R-6uoR1OGc",
      "https://www.youtube.com/embed/tFJnvb4X0Eo",
      "https://www.youtube.com/embed/I61omGj3qE4",
    ],
  },
  {
    agent: "kayo",
    image: "https://i.imgur.com/RsdsqPH.png",
    musics: [
      "https://www.youtube.com/embed/xB-pOc8VOYU",
      "https://www.youtube.com/embed/4p-9om16gm8",
      "https://www.youtube.com/embed/8dVUaIWU8e0",
      "https://www.youtube.com/embed/09DLC5Y0Nwk",
      "https://www.youtube.com/embed/yx2N7B9hyMw",
      "https://www.youtube.com/embed/oL9SgvakmB4",
      "https://www.youtube.com/embed/2Bgb-60LeK8",
      "https://www.youtube.com/embed/7Pv0u7uMn-g",
      "https://www.youtube.com/embed/nVZ6edT2WDU",
      "https://www.youtube.com/embed/uSQt4ckq-dg",
      "https://www.youtube.com/embed/rhtgBXp4pTY",
      "https://www.youtube.com/embed/UbX5E5PFQFM",
      "https://www.youtube.com/embed/bIU7MJwQrjg",
      "https://www.youtube.com/embed/K01IomsbJME",
      "https://www.youtube.com/embed/uQ52WfZfa5I",
      "https://www.youtube.com/embed/Swx4187g_QA",
      "https://www.youtube.com/embed/fQZq1-oRIlA",
    ],
  },
  {
    agent: "chamber",
    image: "https://i.imgur.com/B3SPQoN.png",
    musics: [
      "https://www.youtube.com/embed/Pq3tR8rYFUA",
      "https://www.youtube.com/embed/5UW3oWn60D0",
      "https://www.youtube.com/embed/BqZ_GA4pTTg",
      "https://www.youtube.com/embed/mihk_z7ykgw",
      "https://www.youtube.com/embed/8cVfkFD77AA",
      "https://www.youtube.com/embed/lM9rRMJ3Ayc",
      "https://www.youtube.com/embed/m3t08CLbOb4",
      "https://www.youtube.com/embed/75ROCUXTOOs",
      "https://www.youtube.com/embed/p-ZvHDaR72Q",
      "https://www.youtube.com/embed/udjYJ721vqo",
      "https://www.youtube.com/embed/bZX7nXaEM2c",
      "https://www.youtube.com/embed/FQD_WpsYtiU",
      "https://www.youtube.com/embed/kfzDMDSGcU0",
      "https://www.youtube.com/embed/w4owJamctrI",
      "https://www.youtube.com/embed/ahZD2RILUsg",
      "https://www.youtube.com/embed/7zzaalDa4gY",
      "https://www.youtube.com/embed/A7h1tFFnvdw",
      "https://www.youtube.com/embed/TCd6PfxOy0Y",
      "https://www.youtube.com/embed/uq-N56mddbE",
    ],
  },
  {
    agent: "fade",
    image: "https://i.imgur.com/qkWa0nz.png",
    musics: [
      "https://www.youtube.com/embed/0y_OCiUV5J0",
      "https://www.youtube.com/embed/UKmrgTlfdx8",
      "https://www.youtube.com/embed/5cUmTjosAIg",
      "https://www.youtube.com/embed/QvgdSKXQgUU",
      "https://www.youtube.com/embed/gS-ZK4zUz1Y",
      "https://www.youtube.com/embed/IlOkXSTLecM",
      "https://www.youtube.com/embed/4ofIpn76yRs",
      "https://www.youtube.com/embed/_DcGJLD5BpU",
      "https://www.youtube.com/embed/h_HCc5boI9w",
      "https://www.youtube.com/embed/t01dYTecfS8",
      "https://www.youtube.com/embed/1ZsPPljyFTo",
      "https://www.youtube.com/embed/zDASkn-FLcg",
      "https://www.youtube.com/embed/JkxsHUOuZqc",
      "https://www.youtube.com/embed/46u_Ggsub1A",
      "https://www.youtube.com/embed/VCMWXPCbc2E",
      "https://www.youtube.com/embed/HaB3kpvZN1Y",
      "https://www.youtube.com/embed/H720bEYY0qY",
      "https://www.youtube.com/embed/YpSaBQKloLA",
      "https://www.youtube.com/embed/Sse0m2wZ--s",
    ],
  },
  {
    agent: "harbour",
    image: "https://i.imgur.com/5fFOrEi.png",
    musics: [
      "https://www.youtube.com/embed/M-ZUQjB0yAo",
      "https://www.youtube.com/embed/sXWjwUl949Y",
      "https://www.youtube.com/embed/GjpGhLY1_3s",
      "https://www.youtube.com/embed/tCueJ_CmZsk",
      "https://www.youtube.com/embed/TWDo5EF9kBE",
      "https://www.youtube.com/embed/1unUX3Y2HW4",
      "https://www.youtube.com/embed/KvdSVPB6v_M",
      "https://www.youtube.com/embed/hnswwRWLi3E",
      "https://www.youtube.com/embed/rHMZleMG628",
      "https://www.youtube.com/embed/H8sfC-FFktI",
      "https://www.youtube.com/embed/vEHmjVtqXp8",
      "https://www.youtube.com/embed/vrLYt-wi7a4",
      "https://www.youtube.com/embed/42Ekv1x_Qdo",
      "https://www.youtube.com/embed/tpFljbJxZiw",
      "https://www.youtube.com/embed/T3UWMb9KDTA",
      "https://www.youtube.com/embed/pqPQR9uxN1k",
      "https://www.youtube.com/embed/43v8pWBUJRQ",
    ],
  },
  {
    agent: "gekko",
    image: "https://i.imgur.com/v6uOos0.png",
    musics: [
      "https://www.youtube.com/embed/MHxJXBLJW98",
      "https://www.youtube.com/embed/guQ5r9hc6Ks",
      "https://www.youtube.com/embed/oIo7b1e5Q_Y",
      "https://www.youtube.com/embed/gc3vNc-JhWQ",
      "https://www.youtube.com/embed/ZUu5unXsPL8",
      "https://www.youtube.com/embed/vd-Lp7-AKdU",
      "https://www.youtube.com/embed/C2Yj2NFYV84",
      "https://www.youtube.com/embed/3sOXiL05VSY",
      "https://www.youtube.com/embed/nmPdsM6gyGw",
      "https://www.youtube.com/embed/Yl8RREWwnhQ",
      "https://www.youtube.com/embed/OiO6U23KYuc",
      "https://www.youtube.com/embed/OSdJ-KGdjuI",
      "https://www.youtube.com/embed/RmTeRzOtRsw",
      "https://www.youtube.com/embed/0a4PD4SwEAs",
      "https://www.youtube.com/embed/VRQDOFaFqWk",
      "https://www.youtube.com/embed/z_ipM46uW_Y",
      "https://www.youtube.com/embed/b_HKQp1JGqw",
      "https://www.youtube.com/embed/0pMMpCzd3ek",
    ],
  },
];
